language: node_js
node_js:
  - "node"

script:
  - npm install -g firebase-tools
  - bower install

deploy:
# production
- provider: script
  skip_cleanup: true
  script: "firebase use mlab-oti && firebase deploy --only hosting:mlab-speedtest --token $FIREBASE_TOKEN"
  on:
    repo: m-lab/mlab-speedtest
    tags: true
